services:
  php:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    container_name: php_${APP_ID}
    working_dir: /var/www/html
    volumes:
      - ../www/${APP_ID}/wp:/var/www/html
      - ../composer:/tmp/composer 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_ID}.rule=Host(`${PROJECT_DOMAIN}`)"
      - "traefik.http.services.${APP_ID}.loadbalancer.server.port=80"
    depends_on:
      - db
    networks:
      - web

  db:
    platform: linux/amd64
    image: mariadb:11.6
    container_name: db_${APP_ID}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../www/${APP_ID}/mysql:/var/lib/mysql
    networks:
      - web

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`phpmyadmin.test`)"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
    depends_on:
      - db
    networks:
      - web

  mailhog:
    platform: linux/amd64
    image: axllent/mailpit:latest
    container_name: mailpit
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailpit.rule=Host(`mailpit.test`)"
      - "traefik.http.services.mailpit.loadbalancer.server.port=8025"
    ports:
      - "8025:8025"
    networks:
      - web

  adminer:
    platform: linux/amd64
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.test`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    depends_on:
      - db
    networks:
      - web

  elasticsearch:
    platform: linux/amd64
    image: elasticsearch:7.17.25
    container_name: elasticsearch_${APP_ID}
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=changeme
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../www/${APP_ID}/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9301:9300"
    networks:
      - web

  kibana:
    platform: linux/amd64
    image: kibana:7.17.25
    container_name: kibana_${APP_ID}
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
      XPACK_SECURITY_ENABLED: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana-${APP_ID}.rule=Host(`kibana-${APP_ID}.test`)"
      - "traefik.http.services.kibana-${APP_ID}.loadbalancer.server.port=5601"
    depends_on:
      - elasticsearch
    networks:
      - web

  traefik:
    image: traefik:v3.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - web

networks:
  web:
    external: false
